### ISSUE TITLE
Remove jQuery

### ISSUE THREAD

**Issue by KevinGimbel** [bullgit/clean-your-screen#2]
When exploring the source code I found jQuery. Why is jQuery loaded? 

As of https://github.com/bullgit/clean-your-screen/blob/gh-pages/script.js it seems to be used nowhere in the Application.

**Comment by Haroenv** [comment]
https://github.com/bullgit/clean-your-screen/pull/3

**Comment by reimersjan** [comment]
merged https://github.com/bullgit/clean-your-screen/pull/3
